title: Site

tabs:
  page:
    label: Website
    icon: page
    columns:
      main:
        width: 2/3
        sections:
          homepage:
            label: Homepage
            type: pages
            image: false
            template:
              - home
            sortable: false
            max: 1
          allpages:
            label: Pages
            type: pages
            image: false
            template:
              - page
            sortable: true
      sidebar:
        width: 1/3
        sections:
          uploads:
            type: fields
            fields:
              media:
                label: Upload Files
                type: files
                multiple: true
                link: false
                image:
                  back: "#000"
                  icon: false
                  ratio: 6/3
                  cover: true
          logo:
            type: fields
            fields:
              logo:
                label: Select {{site.title}} Logo
                type: files
                link: false
                template: image
                uploads: false
                multiple: false
                image:
                  back: "#000"
                  icon: false
                  ratio: 6/3
                  cover: true
  # uploads:
  #   label: Website uploads
  #   icon: upload
  #   sections:
  #     uploads:
  #       type: fields
  #       fields:
  #         media:
  #           label: Files
  #           type: files
  #           multiple: true
  #           link: false
  #           image:
  #             back: "#000"
  #             icon: false
  #             ratio: 6/3
  #             cover: true
  menu:
    label: Menu
    icon: menu
    sections:
      mainmenu:
        type: fields
        fields:
          mixedMenu:
            label: Main Menu
            type: structure
            fields:
              linkTitle:
                type: text
                label: Label
              link:
                type: link
                label: Link
                options:
                  - page
                  - url  
              color:
                type: color
                alpha: true 
      dropdownmenu:
        type: fields
        fields:
          blocks:
            label: Dropdown Menu
            type: blocks
            pretty: true
            fieldsets:
              - menu    
  slider:
    label: Text and Press
    icon: grid-right
    sections:
      content:
        type: fields
        fields:
          sliderBlocks:
            label: Items
            width: 2/3
            type: blocks
            pretty: true
            fieldsets:
              - slider   
          sliderLabel:
            label: Change Menu Label
            type: text
            width: 1/3                
  seo:
    label: Website SEO
    icon: search
    columns:
      main:
        width: 2/3
        sections:
          seocontent:
            type: fields
            fields:
              description:
                label: Description
                type: textarea
                buttons: false
              keywords:
                label: Keywords
                type: tags         
      image:
        width: 1/3
        sections:
          image:
            type: fields
            fields:
              ogimage:
                label: Select OG Image
                type: files
                link: false
                template: image
                query: site.images
                uploads: false
                layout: cards
                size: huge
                multiple: false
                image:
                  back: "#000"
                  icon: false
                  ratio: 6/3
                  cover: true



