title: Site

tabs:
  page:
    label: Website pages
    icon: page
    columns:
      main:
        width: 2/3
        sections:
          homepage:
            label: Homepage
            type: pages
            image: false
            template:
              - home
            sortable: false
            max: 1
          allpages:
            label: Pages
            type: pages
            image: false
            template:
              - page
            sortable: true
      sidebar:
        width: 1/3
        sections:
          footer:
            type: fields
            fields:
              footer:
                type: text
                placeholder: Year
                before: "©"
                after: "ALMARE"
  menu:
    label: Menu
    icon: menu
    columns:
      main:
        width: 2/3
        sections:
          mainmenu:
            type: fields
            fields:
              mixedMenu:
                label: Main menu
                type: structure
                fields:
                  linkTitle:
                    type: text
                    label: Label
                  link:
                    type: link
                    label: Link
                    options:
                      - page
                      - url  
                  color:
                    type: color
                    alpha: true 
          dropdownmenu:
            type: fields
            fields:
              blocks:
                label: Dropdown Menu
                type: blocks
                pretty: true
                fieldsets:
                  - menu    
      sidebar:
        width: 1/3
        sections:
          globalFiles:
            type: fields
            fields:
              files:
                type: files    
  slider:
    label: Text and Press
    icon: grid-right
    columns:
      main:
        width: 2/3
        sections:
          content:
            type: fields
            fields:
              sliderBlocks:
                label: Items
                type: blocks
                pretty: true
                fieldsets:
                  - slider                    
      sidebar:
        width: 1/3
        sections:
          files:
            type: fields
            fields:
              sliderFiles:
                label: Files
                type: files
                multiple: true
                link: false
                image:
                  back: "#000"
                  icon: false
                  ratio: 6/3
                  cover: true
  seo:
    label: Website metadata
    icon: search
    columns:
      main:
        width: 2/3
        sections:
          seocontent:
            type: fields
            fields:
              description:
                label: Description
                type: textarea
                buttons: false
              keywords:
                label: Keywords
                type: tags         
      image:
        width: 1/3
        sections:
          image:
            type: fields
            fields:
              ogimage:
                label: OG Image
                type: files
                template: image
                uploads: image
                layout: cards
                size: huge
                multiple: false
                image:
                  back: "#000"
                  icon: false
                  ratio: 6/3
                  cover: true



